### ISSUE TITLE
Application Meta-Features

### ISSUE THREAD

**Issue by AlyxMoon** [AlyxMoon/Lunars-Factorio-Mod-Manager#36]
Not critical to the base functionality of the app, but it would be fun to add the following:

- [ ] An about page
- [ ] Check for app updates
- [ ] Downloading of app updates (and possibly updating itself)
